dist: xenial
language: python
python:
  - "3.7"
services:
  - mongodb
env:
  global:
    -MONGO_DB_URI=mongodb://localhost:27017/mydb_test
install:
  - pip install -r requirements.txt
  - pip install black
script:
  - python -m unittest discover -s tests
  - black app/ --check
